version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carrot-market-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
